### ISSUE TITLE
Sim v0.1

### ISSUE THREAD

**Issue by varqox** [varqox/sim#9]
List of things which should be done for a v0.1 release.
# Tasks
- [ ] Problems administration
  - [ ] Problem editing
    - [ ] Name
    - [ ] Label
    - [ ] Memory limit
    - [ ] Checker
    - [ ] Main solution
    - [ ] Solutions
    - [ ] Tests
    - [x] Rejudge all submissions
    - [x] Package downloading
    - [x] Problem adding / reuploading - allow detecting more tests than it's specified in the Simfile
  - [x] Problemset
    - [ ] Difficulty
    - [x] Tags
    - [x] private/public
- [ ] Users administration
  - [x] Users list
  - [x] User profile editing and deletion
  - [ ] Registration blocking
  - [x] Add user
  - [ ] Ask for password when editing username or email or type or password.
- [ ] Command line options
- [ ] Move to epoll()
- [ ] Different compilers of a submission
- [ ] Languages on the site
- [ ] Processes names
- [ ] FD_OPEN_LIMIT ???
- [ ] Killing a subprocesses (Spawner and server at exit)
- [ ] Main args parser ?
- [ ] BUG: filename cannot contain '/' - possible HTTP header injection
- [ ] Session IP and proxy - create instructions in README
- [ ] Notes - temporary "submissions", useful to save code
- [x] Chdir guard?
- [x] BUG: editing contest when incorrect username => do not accept
- [x] Improve site navigation
  - [x] Side menu
  - [x] Ranking
  - [x] Problems
  - [x] Submit a solution
- [x] Editing profile - ask for password? - Nope
- [x] Submissions list: filters - most importantly 'final'
- [x] Implement some score revealing system
- [x] Removing user account: ask for password
- [x] Logs page 
  - [x] Acquiring more logs
- [x] Notifications
- [x] Judge server
  - [x] Judge worker
  - [x] Problem adding queue
    - [x] Conflict submissions which are judged when problem is edited
  - [x] Failed to open test - bug?
  - [x] Fix submission queue bug
- [x] Submit solutions by pasting the code
- [x] UTC to local time
- [x] Add ignored submissions
- [x] Sandbox: add syscall name in the message (on forbidden syscall error)
- [x] Contests users
  - [x] Participiants (especially in private contests)
  - [x] Moderators
- [x] Submissions administration
  - [x] Submission page
  - [x] Submission list
- [x] Checker compilation report (only if compilation failed)
- [x] Sandbox: CONSUMED MEMORY
- [x] Rename config.conf to Simfile
- [x] Rewirte CppToHTML as library
- [x] Add compilation time limit
- [x] User submissions page
- [x] User profile page
- [x] Configuration files
- [x] Log files
- [x] Files page
- [x] Password reseting
- [x] noexcept everywhere
- [x] MySQL spaces in text fields are truncated - do something with this behaviour!
- [x] HTML space escaping bug - look at forms (via page source) in which field values contain a space
- [x] URI parser
- [x] Password salt
- [x] Ranking #7

**Comment by varqox** [comment]
All relevant tasks were migrated to project board "TODO"
